#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

function requirePath(value, name) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError(`${name} must be a non-empty path`);
  }
  return path.resolve(value);
}

export function renderInstruction({ systemPath, userPath, generatedAt = new Date() }) {
  const resolvedSystem = requirePath(systemPath, 'systemPath');
  const resolvedUser = requirePath(userPath, 'userPath');
  const system = fs.readFileSync(resolvedSystem, 'utf8');
  const user = fs.readFileSync(resolvedUser, 'utf8');
  const timestamp = generatedAt instanceof Date ? generatedAt.toISOString() : String(generatedAt);

  return [
    '<!-- zylos-generated:split-v1',
    `system: ${resolvedSystem}`,
    `user: ${resolvedUser}`,
    `generated: ${timestamp}`,
    'Do not edit this file; customize the user file above.',
    '-->',
    '',
    system.trimEnd(),
    '',
    user.trimEnd(),
    '',
  ].join('\n');
}

export function needsRebuild({ systemPath, userPath, outputPath }) {
  const resolvedSystem = requirePath(systemPath, 'systemPath');
  const resolvedUser = requirePath(userPath, 'userPath');
  const resolvedOutput = requirePath(outputPath, 'outputPath');
  if (!fs.existsSync(resolvedOutput)) return true;
  const outputMtime = fs.statSync(resolvedOutput).mtimeMs;
  return fs.statSync(resolvedSystem).mtimeMs > outputMtime
    || fs.statSync(resolvedUser).mtimeMs > outputMtime;
}

export function assembleInstruction({ systemPath, userPath, outputPath }) {
  const resolvedOutput = requirePath(outputPath, 'outputPath');
  const content = renderInstruction({ systemPath, userPath });
  fs.mkdirSync(path.dirname(resolvedOutput), { recursive: true });
  const tmpPath = `${resolvedOutput}.tmp.${process.pid}.${Date.now()}`;
  try {
    fs.writeFileSync(tmpPath, content, 'utf8');
    fs.renameSync(tmpPath, resolvedOutput);
  } finally {
    try { fs.unlinkSync(tmpPath); } catch { }
  }
  return resolvedOutput;
}

function parseCliArgs(argv) {
  const values = {};
  for (let index = 0; index < argv.length; index += 2) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (!flag?.startsWith('--') || value == null) {
      throw new Error('Usage: assembler.mjs --system PATH --user PATH --output PATH [--marker PATH]');
    }
    values[flag.slice(2)] = value;
  }
  return values;
}

function main() {
  const args = parseCliArgs(process.argv.slice(2));
  if (args.marker && !fs.existsSync(path.resolve(args.marker))) return;
  const paths = {
    systemPath: args.system,
    userPath: args.user,
    outputPath: args.output,
  };
  if (needsRebuild(paths)) assembleInstruction(paths);
}

if (process.argv[1]
  && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))) {
  main();
}
