import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
const require=createRequire(import.meta.url),modulePath=require.resolve('../upgrade-maintenance.cjs'),m=require(modulePath);
const macTest=(name,fn)=>test(name,{skip:process.platform!=='darwin'},fn);
function fixture(t){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'mac-admission-')));fs.chmodSync(dir,0o700);t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
function contender(dir){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,['-e',`try{require(${JSON.stringify(modulePath)}).acquire(${JSON.stringify(dir)});process.stdout.write('owner');}catch(e){process.stdout.write('blocked:'+e.message);}`],{stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);child.on('error',reject);child.on('exit',code=>code?reject(Error(err)):resolve(out));});}
macTest('competing Mac processes admit one owner; owner death never reclaims admission',async t=>{const dir=fixture(t);const results=await Promise.all(Array.from({length:6},()=>contender(dir)));assert.equal(results.filter(s=>s==='owner').length,1);assert.equal(results.filter(s=>s.startsWith('blocked:')).length,5);const before=fs.readFileSync(path.join(dir,'controller.json'));assert.throws(()=>m.acquire(dir),/manual recovery/);assert.deepEqual(fs.readFileSync(path.join(dir,'controller.json')),before);});
macTest('malformed and dead-PID admission cannot be stolen',t=>{const dir=fixture(t),file=path.join(dir,'controller.json');for(const content of ['','{broken',JSON.stringify({pid:2147483647,token:'old',timestamp:0})]){fs.writeFileSync(file,content,{mode:0o600});assert.throws(()=>m.acquire(dir),/manual recovery/);assert.equal(fs.readFileSync(file,'utf8'),content);}});
macTest('live closure holds admission across compensation and cannot be reused after release',t=>{const dir=fixture(t),release=m.acquire(dir);assert.equal(release.withOwnership(dir,()=>{assert.throws(()=>m.acquire(dir),/admission retained/);assert.throws(release,/during recovery/);return 'restored';}),'restored');assert.throws(()=>release.withOwnership(dir+'-other',()=>{}));release();assert.throws(()=>release.withOwnership(dir,()=>{}),/released/);const second=m.acquire(dir);release();assert.throws(()=>m.acquire(dir),/admission retained/);second();});
macTest('changed owner token prevents continuation and release',t=>{const dir=fixture(t),release=m.acquire(dir),file=path.join(dir,'controller.json'),saved=m.read(file);fs.writeFileSync(file,JSON.stringify({...saved,token:'different'}));assert.throws(()=>release.withOwnership(dir,()=>assert.fail('ran without owner')),/ownership changed/);assert.throws(release,/ownership changed/);assert.equal(m.read(file).token,'different');});
macTest('standalone frozen resume refuses even without an admission file and cannot change data',t=>{const dir=fixture(t);fs.copyFileSync(new URL('../upgrade-maintenance.cjs',import.meta.url),path.join(dir,'maintenance.cjs'));fs.copyFileSync(new URL('../upgrade-recovery.cjs',import.meta.url),path.join(dir,'runner.cjs'));const r=require(path.join(dir,'runner.cjs')),frozen=require(path.join(dir,'maintenance.cjs'));fs.writeFileSync(path.join(dir,'database'),'current');let materialReads=0,error;frozen.read=()=>{materialReads++;throw Error('transaction material access forbidden');};try{r.resume(dir);}catch(caught){error=caught;}assert.equal(materialReads,0,'standalone resume must refuse before inspecting transaction materials');assert.match(error?.message||'',/manual recovery/);assert.equal(fs.readFileSync(path.join(dir,'database'),'utf8'),'current');assert.equal(fs.existsSync(path.join(dir,'controller.json')),false);});
